version: "3.9"
services: 
  akriti:
    build: akriti
    container_name: akriti
    ports:
      - 5000:80
    
  proxy:
    build: proxy
    container_name: proxy
    ports:
      - 8080:80
    volumes: 
      - vol.conf:/etc/nginx/conf.d/

volumes: 
  vol.conf:
